#!/usr/bin/env python3
# =============================================================================
# DRYAS  |  Script 009  —  BUILD THE SUBMISSION DOCX
# =============================================================================
# WHAT THIS SCRIPT DOES
#   Assembles manuscript/DRYAS_manuscript_v<N>.md (latest), the three tables
#   generated by 008, the Elsevier-Harvard reference list and the figure
#   captions into one Word document formatted for review: Times New Roman 12 pt,
#   double spacing, continuous line numbers, page numbers, A4. Figures are
#   rasterised from PDF/ (300 dpi) and embedded after their captions so the
#   draft can be read as a whole; for submission the PDFs are uploaded
#   separately.
#
#   Pipeline: markdown --pandoc--> docx --python-docx--> layout tweaks.
#   Requirements: pandoc (brew install pandoc), poppler (brew install poppler),
#   python-docx (uv add python-docx). If pandoc is missing the script stops
#   with an explicit message.
#
# OUTPUTS manuscript/DRYAS_manuscript_v<N>.docx, manuscript/figures_png/*.png
# USAGE   uv run python src/009_build_docx.py [--no-figures]
# =============================================================================

from __future__ import annotations

import argparse
import glob
import re
import shutil
import subprocess
import sys
from pathlib import Path

SRC_DIR = Path(__file__).resolve().parent
ROOT = SRC_DIR.parent
MS_DIR = ROOT / "manuscript"
PDF_DIR = ROOT / "PDF"

FIGURES = [  # (file stem, caption)
    ("003a_array_and_segments", "Fig. 1. Tree-ring sites (numbered triangles; site key at right), approximate seismic source rectangles and catalogued M ≥ 7 events assigned to them (circles scaled by magnitude). Dashed circles show the 80 km radius used in the synthetic testbed."),
    ("002b_preservation_tradeoff", "Fig. 2. Injection–recovery test of five standardisation methods. (a) Median preservation of an injected five-year suppression (A = 0.35) versus variance removed relative to the raw site mean; bars are interquartile ranges over sites; the selected method is ringed in black. (b) Preservation across injected amplitudes (median and interquartile band)."),
    ("004b_prior_calibration", "Fig. 3. Confronting the ground-motion prior with the trees. (a) Response z-score of every (site, event) pair with M ≥ 6.5 inside the usable span versus prior PGA; red points exceed the one-sided 95 % detection threshold. (b) Observed detection rate in PGA bins (point size ∝ number of pairs), the prior logistic declared in Section 2.3, and the logistic fitted by bounded maximum likelihood."),
    ("004a_sea_composites", "Fig. 4. Superposed epoch analysis per site on the events with prior response probability ≥ 0.5 (red), against the 5–95 % range of 2,000 random-year composites of the same size (grey). n is the number of events; p is the one-sided probability of the years 0–1 mean under the null."),
    ("005a_detection_power", "Fig. 5. Single-site detection power. (a) Probability of detection versus injected amplitude at the measured responding fraction f = 0.47. (b) Sensitivity slope dz/dA versus mean living-tree depth with the fitted power law."),
    ("006a_headline_bounds_Af", "Fig. 6. Ninety-five per cent upper bound on stand-mean growth loss in the event year (A × f) versus prior PGA for individual pairs (grey) and for array stacks of M ≥ 7.5 events seen by at least two sites (red, labelled with year, segment, magnitude and number of sites)."),
    ("007a_responsive_fraction_vs_null", "Fig. 7. Fractions of trees classified as responsive under seven published-style criteria at event years (red) and at random years (grey: median and 5–95 % range of the mean over the same number of years), for detrended indices (left) and raw widths (right)."),
    ("005d_array_design", "Fig. 8. Number of coherent sites required to detect a stand-mean growth loss A at 3σ, from the measured sensitivity scaling, for 10–100 trees per site."),
]
SUPP = [("001b_temporal_coverage", "Fig. S1"), ("002a_chronologies_selected", "Fig. S2"), ("002c_eps_sample_depth", "Fig. S3"),
        ("002d_injection_example", "Fig. S4"), ("003b_expected_response_matrix", "Fig. S5"), ("003c_attenuation_curves", "Fig. S6"),
        ("005c_mxd_sea", "Fig. S7"), ("006b_ablation_summary", "Fig. S8"), ("006c_geometry_sensitivity", "Fig. S9"),
        ("007b_pooled_sea_double_bootstrap", "Fig. S10"), ("007c_lag_tolerant_and_resilience", "Fig. S11")]


def latest_manuscript() -> Path:
    c = sorted(glob.glob(str(MS_DIR / "DRYAS_manuscript_v*.md")), key=lambda p: int(re.search(r"_v(\d+)", p).group(1)))
    if not c:
        sys.exit("no manuscript/DRYAS_manuscript_v*.md found")
    return Path(c[-1])


def rasterise(stem: str, out_dir: Path) -> Path | None:
    pdf = PDF_DIR / f"{stem}.pdf"
    if not pdf.exists():
        return None
    out_dir.mkdir(exist_ok=True)
    target = out_dir / stem
    if shutil.which("pdftoppm") is None:
        return None
    subprocess.run(["pdftoppm", "-r", "300", "-png", "-singlefile", str(pdf), str(target)], check=False)
    p = out_dir / f"{stem}.png"
    return p if p.exists() else None


def assemble_markdown(ms: Path, with_figures: bool) -> str:
    text = ms.read_text(encoding="utf-8")
    # drop the draft-only header lines and placeholders sections at the end
    body = text.split("## Tables")[0]
    body = re.sub(r"^Target journal:.*?\n\n", "", body, flags=re.S | re.M)
    body = body.replace("Items in 【 】 are to be filled or confirmed before submission.\n", "")
    # reference list
    refs = (MS_DIR / "references_elsevier_harvard.md").read_text(encoding="utf-8")
    refs = "\n\n".join(l.strip() for l in refs.splitlines() if l.strip() and not l.startswith("#"))
    refs = re.sub(r"\s*(✔|\(v\)|\(author list v\)|\(co-authors to confirm\))", "", refs)
    body = re.sub(r"## References\n.*", "## References\n\n" + refs + "\n", body, flags=re.S)
    parts = [body]
    # tables
    for stem in ("table1_sites", "table2_array_bounds", "table3_tests", "table4_array_design"):
        p = MS_DIR / f"{stem}.md"
        if p.exists():
            parts.append("\n\n" + p.read_text(encoding="utf-8"))
    # figure captions (+ images)
    parts.append("\n\n## Figure captions\n")
    fig_dir = MS_DIR / "figures_png"
    for stem, cap in FIGURES:
        parts.append(f"\n{cap}\n")
        if with_figures:
            png = rasterise(stem, fig_dir)
            if png:
                parts.append(f"\n![]({png.as_posix()}){{width=16cm}}\n")
    parts.append("\n\n## Supplementary figures (captions)\n")
    for stem, lab in SUPP:
        parts.append(f"\n{lab}. {stem.replace('_', ' ')} (PDF/{stem}.pdf).\n")
    return "".join(parts)


def postprocess(docx_path: Path):
    try:
        from docx import Document
        from docx.shared import Pt, Cm
        from docx.oxml.ns import qn
        from docx.oxml import OxmlElement
    except ImportError:
        print("  python-docx not installed (uv add python-docx); layout tweaks skipped")
        return
    d = Document(str(docx_path))
    for st in d.styles:
        try:
            st.font.name = "Times New Roman"
        except Exception:
            pass
    normal = d.styles["Normal"]; normal.font.size = Pt(12)
    normal.paragraph_format.line_spacing = 2.0
    for s in d.sections:
        s.page_width, s.page_height = Cm(21.0), Cm(29.7)
        s.left_margin = s.right_margin = s.top_margin = s.bottom_margin = Cm(2.5)
        sectPr = s._sectPr
        ln = OxmlElement("w:lnNumType"); ln.set(qn("w:countBy"), "1"); ln.set(qn("w:restart"), "continuous")
        sectPr.append(ln)
        # page number in footer
        footer = s.footer.paragraphs[0] if s.footer.paragraphs else s.footer.add_paragraph()
        run = footer.add_run()
        for tag, txt in (("begin", None), (None, "PAGE"), ("end", None)):
            if tag:
                el = OxmlElement("w:fldChar"); el.set(qn("w:fldCharType"), tag); run._r.append(el)
            else:
                el = OxmlElement("w:instrText"); el.set(qn("xml:space"), "preserve"); el.text = txt; run._r.append(el)
    from docx.shared import RGBColor
    for p in d.paragraphs:
        if p.style.name.startswith("Heading") or p.style.name == "Title":
            p.paragraph_format.line_spacing = 1.5
            for r in p.runs:
                r.font.color.rgb = RGBColor(0, 0, 0); r.font.name = "Times New Roman"
    for t in d.tables:
        for row in t.rows:
            for cell in row.cells:
                for p in cell.paragraphs:
                    p.paragraph_format.line_spacing = 1.0
                    for r in p.runs:
                        r.font.size = Pt(9)
    d.save(str(docx_path))


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--no-figures", action="store_true")
    args = ap.parse_args()
    if shutil.which("pandoc") is None:
        sys.exit("pandoc not found: brew install pandoc (macOS) / apt install pandoc (Linux)")
    ms = latest_manuscript()
    md = assemble_markdown(ms, with_figures=not args.no_figures)
    tmp = MS_DIR / "_assembled.md"
    tmp.write_text(md, encoding="utf-8")
    out = ms.with_suffix(".docx")
    subprocess.run(["pandoc", str(tmp), "-o", str(out), "--from", "markdown+pipe_tables", "--to", "docx"], check=True)
    postprocess(out)
    words = len(re.sub(r"!\[.*?\]\(.*?\)", "", md.split("## References")[0]).split())
    print(f"  wrote {out}  (main text ~{words} words before references)")
    print("Done.")


if __name__ == "__main__":
    sys.exit(main())
