#!/usr/bin/env python3
# =============================================================================
# DRYAS  |  Script 011  —  SUBMISSION PACKAGE (highlights, cover letter, supplementary)
# =============================================================================
# Builds manuscript/submission/ with:
#   highlights.docx, cover_letter.docx, suggested_reviewers.docx,
#   supplementary.docx (Text S1 = data/006_preregistration_record.md inserted,
#   Text S2, S-figure captions) and copies of the S-figure PDFs renamed S1..S11.
# USAGE  uv run python src/011_submission_package.py   (needs pandoc)
# =============================================================================
import re, shutil, subprocess, sys
from pathlib import Path
ROOT = Path(__file__).resolve().parent.parent
MS, DATA, PDF = ROOT / "manuscript", ROOT / "data", ROOT / "PDF"
OUT = MS / "submission"; OUT.mkdir(exist_ok=True)
if shutil.which("pandoc") is None:
    sys.exit("pandoc not found")
prereg = (DATA / "006_preregistration_record.md").read_text(encoding="utf-8") if (DATA / "006_preregistration_record.md").exists() else "(run 006 first)"
prereg = "\n".join(l.replace("# DRYAS — Pre-registration record (auto-generated by 006)", "").replace("## ", "### ") for l in prereg.splitlines())
supp = (MS / "supplementary.md").read_text(encoding="utf-8").replace("@@PREREG@@", prereg)
(OUT / "supplementary_assembled.md").write_text(supp, encoding="utf-8")
for src, dst in (("highlights.md", "highlights.docx"), ("cover_letter.md", "cover_letter.docx"),
                 ("suggested_reviewers.md", "suggested_reviewers.docx"), ("submission/supplementary_assembled.md", "supplementary.docx")):
    subprocess.run(["pandoc", str(MS / src), "-o", str(OUT / dst)], check=True); print("  wrote", OUT / dst)
sfigs = ["001b_temporal_coverage", "002a_chronologies_selected", "002c_eps_sample_depth", "002d_injection_example",
         "003b_expected_response_matrix", "003c_attenuation_curves", "005c_mxd_sea", "006b_ablation_summary",
         "006c_geometry_sensitivity", "007b_pooled_sea_double_bootstrap", "007c_lag_tolerant_and_resilience"]
mfigs = ["003a_array_and_segments", "002b_preservation_tradeoff", "004b_prior_calibration", "004a_sea_composites",
         "005a_detection_power", "006a_headline_bounds_Af", "007a_responsive_fraction_vs_null", "005d_array_design"]
for i, s in enumerate(mfigs, 1):
    if (PDF / f"{s}.pdf").exists(): shutil.copy(PDF / f"{s}.pdf", OUT / f"Figure_{i}.pdf")
for i, s in enumerate(sfigs, 1):
    if (PDF / f"{s}.pdf").exists(): shutil.copy(PDF / f"{s}.pdf", OUT / f"Figure_S{i}.pdf")
print("  copied Figure_1..8.pdf and Figure_S1..S11.pdf to", OUT); print("Done.")
